#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: app-mp
  labels:
    app: app-mp
spec:
  type: NodePort
  selector:
    app: app-mp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app-mp
  labels:
    kube-monkey/enabled: enabled
    kube-monkey/identifier: app-mp
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed-percent"
    kube-monkey/kill-value: '70'  
spec:
  replicas: 30
  template:
    metadata:
      labels:
        app: app-mp
        version: v1
        kube-monkey/enabled: enabled
        kube-monkey/identifier: app-mp
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed-percent"
        kube-monkey/kill-value: '70'        
    spec:
      containers:
      - name: app-mp
        image: eldermoraes/app-mp-oke
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
